import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import { fetchOutputs } from '../lib/contentful';

interface Props {
  outputs: any;
}

const Home: NextPage<Props> = ({ outputs }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        test
        {outputs?.map((output: any) => {
          return <p key={output.sys.id}>{output.fields.name}</p>;
        })}
      </main>
    </div>
  );
};

export default Home;

export const getServerSideProps = async () => {
  const outputs = await fetchOutputs();
  console.log(outputs);
  return {
    props: {
      outputs,
    },
  };
};
